{ pkgs, inputs, ... }:
{
  imports = [
    # Generated by the installer. See the note in the file itself.
    ./hardware-configuration.nix

    # Framework Laptop 13, 12th Gen Intel. Handles the quirks you would
    # otherwise be chasing down one forum thread at a time: kernel params
    # for suspend, the ambient light sensor, brightness key handling,
    # thermald and fwupd defaults, and the Framework EC kernel module.
    inputs.nixos-hardware.nixosModules.framework-12th-gen-intel

    # Everything shared lives in modules/nixos.
    ../../modules/nixos

    # No GPU module: this machine is Iris Xe only. modules/nixos/gpu-nvidia.nix
    # is left in the repo for whenever you add a second host that needs it.
  ];

  networking.hostName = "nixos-laptop";

  # --- Framework specifics -------------------------------------------------

  # Exposes EC functionality (battery charge limit, privacy switches,
  # system LEDs) through normal sysfs interfaces. nixos-hardware turns
  # this on by default for kernel 6.10+, so this is documentation as much
  # as configuration.
  hardware.framework.enableKmod = true;

  # Goodix fingerprint reader. After the first rebuild, enrol with:
  #   fprintd-enroll
  # then check it with `fprintd-verify`. GNOME picks it up automatically
  # for the lock screen; sudo needs pam config you have not asked for.
  services.fprintd.enable = true;

  environment.systemPackages = with pkgs; [
    # EC access from userspace: charge limits, fan curves, LED control.
    # If the attribute is missing on your channel, try fw-ectool instead.
    framework-tool
  ];

  # Battery charge limit. The Framework way is either the BIOS setting
  # (Advanced > Battery charge limit) or the sysfs interface below; the
  # commented-out TLP thresholds in modules/nixos/power.nix will not work
  # here unmodified, because Framework enumerates the battery as BAT1
  # rather than BAT0.
  #
  # systemd.services.battery-charge-limit = {
  #   wantedBy = [ "multi-user.target" ];
  #   after = [ "multi-user.target" ];
  #   serviceConfig.Type = "oneshot";
  #   script = ''
  #     echo 80 > /sys/class/power_supply/BAT1/charge_control_end_threshold
  #   '';
  # };

  # Firmware comes from LVFS and Framework push BIOS updates there.
  # services.fwupd is already enabled in modules/nixos/hardware.nix, so:
  #   fwupdmgr refresh && fwupdmgr update
  # Have a live USB to hand before running a BIOS update.

  # The release you first installed. Do NOT bump this when you upgrade
  # NixOS; it exists so stateful services know which migrations to run.
  system.stateVersion = "26.05";
}
