#!/usr/bin/env bash

# set -e

# CONFIG="install.conf.yaml"
# DOTBOT_DIR="dotbot"

# DOTBOT_BIN="bin/dotbot"
# BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# cd "${BASEDIR}"
# git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
# git submodule update --init --recursive "${DOTBOT_DIR}"

# "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

echo " <<< Do not run the install binary in this branch >>> "
echo " 1. Checkout branch that matches OS (arm-macos, intell-macos, or ubuntu) "
echo " 2. Run the install binary"