[settings]
default_disable = false
default_keys = true
mouse_hides_on_focus = false
group_bars.thickness = 4

[settings.experimental]
status_icon.space_index = true

[keys]
"Alt + Space" = "disable"
"Alt + Shift + Tab" = "toggle_window_floating"
"Alt + Tab" = "toggle_focus_floating"
