# force guake to use Wayland
#export GUAKE_ENABLE_WAYLAND=1
# force mozila firefox to use Wayland
export MOZ_ENABLE_WAYLAND=1

fuction exists() {
    # `command -v` is similar to `which`
    command -v $1 >/dev/null 2>&1
    # more explicitly written as...
    # command -v $1 1>/dev/null 2>/dev/null
}

. "$HOME/.cargo/env"
