# Prompt
eval "$(starship init zsh)"


# ZSH Options
# Key Binds
# disable XON/XOFF to allow ^Q and ^S binds to work
stty -ixon
# (tip: use CTRL-V to find esc-sequences)
# bind arrow keys to search history
bindkey '^[[A' history-beginning-search-backward
bindkey '^[[B' history-beginning-search-forward
# bind PgUp and PgDn keys to history substring search
bindkey '^[[5~' history-substring-search-up
bindkey '^[[6~' history-substring-search-down
# bind Home and End to expected behaviour
bindkey '\e[H'    beginning-of-line
bindkey '\e[F'    end-of-line

# Variables
# syntax highlighting for man pages using bat
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export NULLCMD=bat
export GH_TOKEN=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


# zsh history settings
export HISTFILE=~/.zsh_history  # History filepath
export HISTSIZE=10000   # Maximum events for internal history
export SAVEHIST=100000  # Maximum events in history file

# nvm
export NVM_DIR="$HOME/.nvm"
# This loads nvm
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"
# This loads nvm bash_completion
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"


# Aliases
source ~/.dotfiles/aliases/aliases
source ~/.dotfiles/aliases/git-aliases

# Functions
fuction mkcd() {
    mkdir -p "$@" && cd "$_";
}


# $PATH Location
# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
# yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
# kubernetes-cli
export PATH="/opt/homebrew/opt/kubernetes-cli/bin:$PATH"
#jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
# Add .NET Core SDK tools
export PATH="$PATH:$HOME/.dotnet/tools"


# Plugins
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-history-substring-search/zsh-history-substring-search.zsh
# syntax highlighting must be last to apply to other plugins
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# Completion
autoload -U compinit; compinit
# case-insensitive completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'


# Other
# direnv
eval "$(direnv hook zsh)"
